ambassador:
  image: cpuguy83/docker-grand-ambassador:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: -name atlassiantestdocker_nginx_1 -name atlassiantestdocker_jira_1 -name atlassiantestdocker_stash_1 -name atlassiantestdocker_bamboo_1 -name atlassiantestdocker_postgres_1

jiraFiles:
  image: pghalliday/jira:latest
  command: true

stashFiles:
  image: pghalliday/stash:latest
  command: true

bambooFiles:
  image: pghalliday/bamboo:latest
  command: true

postgresFiles:
  image: postgres:latest
  command: true

nginx:
  image: nginx:latest
  links:
    - ambassador:jira.test.net
    - ambassador:stash.test.net
    - ambassador:bamboo.test.net
  volumes:
    - jira.conf:/etc/nginx/conf.d/jira.conf
    - stash.conf:/etc/nginx/conf.d/stash.conf
    - bamboo.conf:/etc/nginx/conf.d/bamboo.conf
  ports:
    - 0.0.0.0:80:80

jira:
  image: pghalliday/jira:latest
  environment:
    - JIRA_PROXY_NAME=jira.test.net
    - JIRA_PROXY_PORT=80
  links:
    - ambassador:postgres.test.net
    - ambassador:jira.test.net
    - ambassador:stash.test.net
    - ambassador:bamboo.test.net
  volumes_from:
    - jiraFiles

stash:
  image: pghalliday/stash:latest
  environment:
    - STASH_PROXY_NAME=stash.test.net
    - STASH_PROXY_PORT=80
  links:
    - ambassador:postgres.test.net
    - ambassador:jira.test.net
    - ambassador:stash.test.net
    - ambassador:bamboo.test.net
  volumes_from:
    - stashFiles
  ports:
    - 0.0.0.0:7999:7999

bamboo:
  image: pghalliday/bamboo:latest
  environment:
    - BAMBOO_PROXY_NAME=bamboo.test.net
    - BAMBOO_PROXY_PORT=80
  links:
    - ambassador:postgres.test.net
    - ambassador:jira.test.net
    - ambassador:stash.test.net
    - ambassador:bamboo.test.net
  volumes_from:
    - bambooFiles

postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  volumes:
    - jira.sh:/docker-entrypoint-initdb.d/jira.sh
    - stash.sh:/docker-entrypoint-initdb.d/stash.sh
    - bamboo.sh:/docker-entrypoint-initdb.d/bamboo.sh
  volumes_from:
    - postgresFiles
