ambassador:
  image: cpuguy83/docker-grand-ambassador:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: >
    - name atlassiantestdocker_postgres_1
    - name atlassiantestdocker_crowd_1
    - name atlassiantestdocker_jira_1
    - name atlassiantestdocker_stash_1
    - name atlassiantestdocker_bamboo_1
    - name atlassiantestdocker_confluence_1
    - name atlassiantestdocker_nginx_1

postgresFiles:
  image: postgres:latest
  command: "true"
postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  volumes:
    - crowd.sh:/docker-entrypoint-initdb.d/crowd.sh
    - jira.sh:/docker-entrypoint-initdb.d/jira.sh
    - stash.sh:/docker-entrypoint-initdb.d/stash.sh
    - bamboo.sh:/docker-entrypoint-initdb.d/bamboo.sh
    - confluence.sh:/docker-entrypoint-initdb.d/confluence.sh
  volumes_from:
    - postgresFiles

crowdFiles:
  image: pghalliday/crowd:latest
  command: "true"
crowd:
  image: pghalliday/crowd:latest
  environment:
    - CROWD_PROXY_NAME=auth.peerpont.com
    - CROWD_PROXY_PORT=80
    - CROWDID_POSTGRES_HOST=postgres.peerpont.com
    - CROWDID_POSTGRES_PORT=5432
    - CROWDID_POSTGRES_USER=crowdid
    - CROWDID_POSTGRES_PASSWORD=crowdid
    - CROWDID_POSTGRES_DATABASE=crowdid
    - CROWD_XML=/crowd.xml
  volumes:
    - crowd.xml:/crowd.xml
  links:
    - ambassador:postgres.peerpont.com
    - ambassador:auth.peerpont.com
    - ambassador:jira.peerpont.com
    - ambassador:stash.peerpont.com
    - ambassador:build.peerpont.com
    - ambassador:wiki.peerpont.com
  volumes_from:
    - crowdFiles

jiraFiles:
  image: jira:latest
  command: "true"
jira:
  image: jira:latest
  environment:
    - JIRA_PROXY_NAME=jira.peerpont.com
    - JIRA_PROXY_PORT=80
    - JIRA_CROWD_APPLICATION_NAME=jira
    - JIRA_CROWD_APPLICATION_PASSWORD=jira
    - JIRA_CROWD_BASE_URL=http://auth.peerpont.com/crowd
    - JIRA_CROWD_SESSION_VALIDATION_INTERVAL=2
  links:
    - ambassador:postgres.peerpont.com
    - ambassador:auth.peerpont.com
    - ambassador:jira.peerpont.com
    - ambassador:stash.peerpont.com
    - ambassador:build.peerpont.com
    - ambassador:wiki.peerpont.com
  volumes_from:
    - jiraFiles

stashFiles:
  image: stash:latest
  command: "true"
stash:
  image: stash:latest
  environment:
    - STASH_PROXY_NAME=stash.peerpont.com
    - STASH_PROXY_PORT=80
  links:
    - ambassador:postgres.peerpont.com
    - ambassador:auth.peerpont.com
    - ambassador:jira.peerpont.com
    - ambassador:stash.peerpont.com
    - ambassador:build.peerpont.com
    - ambassador:wiki.peerpont.com
  volumes_from:
    - stashFiles
  ports:
    - 0.0.0.0:7999:7999

bambooFiles:
  image: pghalliday/bamboo:latest
  command: "true"
bamboo:
  image: pghalliday/bamboo:latest
  environment:
    - BAMBOO_PROXY_NAME=build.peerpont.com
    - BAMBOO_PROXY_PORT=80
  links:
    - ambassador:postgres.peerpont.com
    - ambassador:auth.peerpont.com
    - ambassador:jira.peerpont.com
    - ambassador:stash.peerpont.com
    - ambassador:build.peerpont.com
    - ambassador:wiki.peerpont.com
  volumes_from:
    - bambooFiles

confluenceFiles:
  image: pghalliday/confluence:latest
  command: "true"
confluence:
  image: pghalliday/confluence:latest
  environment:
    - CONFLUENCE_PROXY_NAME=wiki.peerpont.com
    - CONFLUENCE_PROXY_PORT=80
  links:
    - ambassador:postgres.peerpont.com
    - ambassador:auth.peerpont.com
    - ambassador:jira.peerpont.com
    - ambassador:stash.peerpont.com
    - ambassador:build.peerpont.com
    - ambassador:wiki.peerpont.com
  volumes_from:
    - confluenceFiles

nginx:
  image: nginx:latest
  links:
    - ambassador:auth.peerpont.com
    - ambassador:jira.peerpont.com
    - ambassador:stash.peerpont.com
    - ambassador:build.peerpont.com
    - ambassador:wiki.peerpont.com
  volumes:
    - crowd.conf:/etc/nginx/conf.d/crowd.conf
    - jira.conf:/etc/nginx/conf.d/jira.conf
    - stash.conf:/etc/nginx/conf.d/stash.conf
    - bamboo.conf:/etc/nginx/conf.d/bamboo.conf
    - confluence.conf:/etc/nginx/conf.d/confluence.conf
  ports:
    - 0.0.0.0:80:80
